services:
  - type: web
    name: user-management-dashboard
    runtime: node
    buildCommand: npm install --include=dev && npm install --prefix server --include=dev && npm run build:render
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./dev.db
      - key: PORT
        value: 10000
