services:
  - type: web
    name: user-management-dashboard
    runtime: node
    buildCommand: npm install && npm install --prefix server && npm run db:push --prefix server && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./dev.db
      - key: PORT
        value: 10000
